<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "registrations".
 *
 * @property int $id
 * @property string $type Тип регистрации
 * @property string $fio ФИО
 * @property string $email Email
 * @property int $is_employer ИП
 * @property string $inn ИНН
 * @property string $company_name Название компании
 */
class Registrations extends \yii\db\ActiveRecord
{
    const TYPE_USER = 'user'; // Физ. лицо
    const TYPE_COMPANY = 'company'; // Юр. лицо

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'registrations';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['type', 'fio', 'email'], 'required'],
            [['email'], 'email'],
            [['type'], 'in', 'range' => [self::TYPE_USER, self::TYPE_COMPANY]],
            [['is_employer'], 'integer'],
            [['company_name'], 'validateCompanyName', 'skipOnEmpty' => false],
            ['inn', 'validateInn', 'skipOnEmpty' => false],
            [['email', 'inn'], 'unique'],
            [['fio', 'email', 'inn', 'company_name'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'type' => 'Тип записи',
            'fio' => 'ФИО',
            'email' => 'Email',
            'is_employer' => 'ИП',
            'inn' => 'ИНН',
            'company_name' => 'Название компании',
        ];
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->type = self::TYPE_USER;
    }

    /**
     * Валидация поля ИНН
     * @param $attribute
     * @param $params
     */
    public function validateInn($attribute, $params)
    {
        //  для физ лиц ИНН состоит из 12 цифр
        if ($this->type == self::TYPE_USER && (!empty($this->is_employer) || !empty($this->$attribute)))
        {
            if (!preg_match('/^[0-9]{12}$/', $this->$attribute)) {
                $this->addError($attribute, 'Для физ.лица ИНН должен состоять из 12 цифр');
            }
        }
        //  для юр лиц ИНН состоит из 10 цифр
        else if ($this->type == self::TYPE_COMPANY) {
            if (!preg_match('/^[0-9]{10}$/', $this->$attribute)) {
                $this->addError($attribute, 'Для юр.лица ИНН должен состоять из 10 цифр');
            }
        }
    }

    /**
     * Валидация поля Название компании
     * @param $attribute
     * @param $params
     */
    public function validateCompanyName($attribute, $params)
    {
        if ($this->type == self::TYPE_COMPANY)
        {
            $value = trim($this->$attribute);
            if (!mb_strlen($value)) {
                $this->addError($attribute, 'Название компании не может быть пустым');
            }
        }
    }
}
